name: Build & Deploy to Render

on:
  push:
    branches: [ "main" ]   # cambia si despliegas desde otra rama
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build & test (Maven)
        run: ./mvnw -B verify

      # (Opcional) Sube el JAR como artefacto del workflow
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"
